import test from 'node:test';
import assert from 'node:assert/strict';
import {
  NODE_IDS,
  STANDARD_TOPOLOGY,
  STANDARD_GRAPH,
  findBoardLinePath,
  isOnSingleBoardLine,
} from '../miniprogram/domain/index.ts';

const expectedLines = [
  ['H1', ['P01', 'P02', 'P03', 'P04', 'P05']],
  ['H2', ['P06', 'P07', 'P08', 'P09', 'P10']],
  ['H3', ['P11', 'P12', 'P13', 'P14', 'P15']],
  ['H4', ['P16', 'P17', 'P18', 'P19', 'P20']],
  ['H5', ['P21', 'P22', 'P23', 'P24', 'P25']],
  ['V1', ['P01', 'P06', 'P11', 'P16', 'P21']],
  ['V2', ['P02', 'P07', 'P12', 'P17', 'P22']],
  ['V3', ['P29', 'P27', 'P03', 'P08', 'P13', 'P18', 'P23']],
  ['V4', ['P04', 'P09', 'P14', 'P19', 'P24']],
  ['V5', ['P05', 'P10', 'P15', 'P20', 'P25']],
  ['D1', ['P01', 'P07', 'P13', 'P19', 'P25']],
  ['D2', ['P03', 'P09', 'P15']],
  ['D3', ['P11', 'P17', 'P23']],
  ['D4', ['P05', 'P09', 'P13', 'P17', 'P21']],
  ['D5', ['P03', 'P07', 'P11']],
  ['D6', ['P15', 'P19', 'P23']],
  ['T1', ['P26', 'P27', 'P28']],
  ['T2', ['P29', 'P26']],
  ['T3', ['P26', 'P03']],
  ['T4', ['P29', 'P28']],
  ['T5', ['P28', 'P03']],
] as const;

test('legal nodes are exactly P01 through P29', () => {
  assert.deepEqual(NODE_IDS, Array.from({ length: 29 }, (_, index) => `P${String(index + 1).padStart(2, '0')}`));
  assert.deepEqual(STANDARD_TOPOLOGY.nodes.map(node => node.id), NODE_IDS);
});

test('declared BoardLines exactly match the authoritative IDs and node order', () => {
  assert.deepEqual(STANDARD_TOPOLOGY.lines.map(line => [line.id, line.nodes]), expectedLines);
});

test('the declared BoardLine count matches the required total', () => {
  assert.equal(STANDARD_TOPOLOGY.lines.length, 21);
});

test('BoardGraph has exactly the direct adjacency pairs generated by consecutive line nodes', () => {
  const expected = new Map<string, Set<string>>(NODE_IDS.map(id => [id, new Set()]));
  for (const [, nodes] of expectedLines) {
    for (let index = 1; index < nodes.length; index++) {
      expected.get(nodes[index - 1])!.add(nodes[index]);
      expected.get(nodes[index])!.add(nodes[index - 1]);
    }
  }
  for (const id of NODE_IDS) {
    assert.deepEqual(new Set(STANDARD_GRAPH.neighbors(id)), expected.get(id), id);
    for (const other of NODE_IDS) {
      assert.equal(STANDARD_GRAPH.areAdjacent(id, other), expected.get(id)!.has(other), `${id}-${other}`);
    }
  }
});

test('V3 contains P29-P27-P03 and supports the line path from P29 to P03', () => {
  assert.equal(isOnSingleBoardLine(['P29', 'P27', 'P03'], STANDARD_TOPOLOGY), true);
  assert.deepEqual(findBoardLinePath('P29', 'P03', STANDARD_TOPOLOGY), {
    lineId: 'V3', nodes: ['P29', 'P27', 'P03'],
  });
  assert.equal(STANDARD_GRAPH.areAdjacent('P29', 'P03'), false);
  assert.equal(STANDARD_GRAPH.areAdjacent('P29', 'P27'), true);
  assert.equal(STANDARD_GRAPH.areAdjacent('P27', 'P03'), true);
});

test('separate temple edge lines cannot be merged into one straight BoardLine', () => {
  assert.equal(isOnSingleBoardLine(['P29', 'P26', 'P03'], STANDARD_TOPOLOGY), false);
  assert.equal(isOnSingleBoardLine(['P29', 'P28', 'P03'], STANDARD_TOPOLOGY), false);
  assert.equal(STANDARD_GRAPH.areAdjacent('P29', 'P26'), true);
  assert.equal(STANDARD_GRAPH.areAdjacent('P26', 'P03'), true);
  assert.equal(STANDARD_GRAPH.areAdjacent('P29', 'P28'), true);
  assert.equal(STANDARD_GRAPH.areAdjacent('P28', 'P03'), true);
});

test('temple line connections remain direct graph edges', () => {
  assert.equal(STANDARD_GRAPH.areAdjacent('P26', 'P27'), true);
  assert.equal(STANDARD_GRAPH.areAdjacent('P27', 'P28'), true);
  assert.equal(STANDARD_GRAPH.areAdjacent('P03', 'P08'), true);
  assert.equal(STANDARD_GRAPH.areAdjacent('P26', 'P28'), false);
});
